spring:
  datasource:
#    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://95.111.246.156:5432/postgres
    username: postgres
    password: gBPgSqDCCUJnqpxv
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
server:
  servlet:
    context-path: /api/aripari
  port: 8080