spring:
  datasource:
#    driver-class-name: org.postgresql.Driver

      url: jdbc:postgresql://localhost:5432/postgres
      #    url: jdbc:postgresql://95.111.246.156:5432/postgres
      username: postgres
      password: root
  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
server:
  servlet:
    context-path: /api/aripari
  port: 8080
springdoc:
  api-docs:
    path: /api-docs